/// Paths to the sliced artwork. Generated by `tool/slice_assets.dart`; edit the
/// tool rather than adding stray files here.
abstract final class AppImages {
  static const _dir = 'assets/images';

  // Backdrops.
  static const nightRoute = '$_dir/bg_night_route.webp';
  static const route = '$_dir/bg_route.webp';
  static const track = '$_dir/bg_track.webp';

  // Launch artwork.
  static const launchPortrait = '$_dir/launch_portrait.webp';
  static const launchLandscape = '$_dir/launch_landscape.webp';
  static const wordmark = '$_dir/wordmark.webp';

  // Start marker.
  static const chickenIdle = '$_dir/chicken_idle.png';
  static const chickenRunning = '$_dir/chicken_running.png';
  static const chickenFinished = '$_dir/chicken_finished.png';

  // Checkpoint marker.
  static const eggPending = '$_dir/egg_pending.png';
  static const eggActive = '$_dir/egg_active.png';
  static const eggPassed = '$_dir/egg_passed.png';

  // Tempo-change marker.
  static const coinPending = '$_dir/coin_pending.png';
  static const coinActive = '$_dir/coin_active.png';
  static const coinPassed = '$_dir/coin_passed.png';

  // Recovery marker.
  static const featherLight = '$_dir/feather_light.png';
  static const featherCream = '$_dir/feather_cream.png';
  static const featherGold = '$_dir/feather_gold.png';

  // Stage nodes.
  static const checkpointPending = '$_dir/checkpoint_pending.png';
  static const checkpointActive = '$_dir/checkpoint_active.png';
  static const checkpointDone = '$_dir/checkpoint_done.png';
  static const checkpointFinish = '$_dir/checkpoint_finish.png';

  // Tempo badges.
  static const tempoWalk = '$_dir/tempo_walk.png';
  static const tempoEasyRun = '$_dir/tempo_easy_run.png';
  static const tempoRun = '$_dir/tempo_run.png';
  static const tempoFastRun = '$_dir/tempo_fast_run.png';

  // Road pieces.
  static const roadStraight = '$_dir/road_straight.png';
  static const roadCurve = '$_dir/road_curve.png';
  static const roadLoop = '$_dir/road_loop.png';
  static const roadFinish = '$_dir/road_finish.png';

  // Direction glyphs.
  static const arrowAhead = '$_dir/arrow_ahead.png';
  static const arrowLeft = '$_dir/arrow_left.png';
  static const arrowRight = '$_dir/arrow_right.png';
  static const arrowTurnaround = '$_dir/arrow_turnaround.png';

  // Statistics decorations.
  static const statTrend = '$_dir/stat_trend.png';
  static const statShare = '$_dir/stat_share.png';
  static const statVolume = '$_dir/stat_volume.png';

  // Route strip illustrations.
  static const routeStartFinish = '$_dir/route_start_finish.png';
  static const routeCheckpoint = '$_dir/route_checkpoint.png';
  static const routeTempo = '$_dir/route_tempo.png';
  static const routeRecovery = '$_dir/route_recovery.png';

  // Full illustrations.
  static const illustrationEmpty = '$_dir/illustration_empty.png';
  static const illustrationComplete = '$_dir/illustration_complete.png';

  /// Everything the startup sequence decodes up front, so the first screens
  /// never pop in. Kept in one place so the loading weights stay accurate.
  static const preloadOnStartup = <String>[
    nightRoute,
    route,
    track,
    wordmark,
    chickenIdle,
    chickenRunning,
    eggPending,
    coinPending,
    featherLight,
    checkpointPending,
    checkpointActive,
    checkpointDone,
    checkpointFinish,
    tempoWalk,
    tempoEasyRun,
    tempoRun,
    tempoFastRun,
    roadStraight,
    roadCurve,
    roadFinish,
    illustrationEmpty,
  ];
}
